# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Strange Ideas'
tagline:          'My musings'
description:      'Fill in Later'
url:              http://www.eldritchideen.com
baseurl:          /

author:
  name:           'Steven Cook'
  url:            http://www.eldritchideen.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/eldritchideen/
